services:
  lms-server:
    container_name: lms-server
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=18
        - ENVIRONMENT=development
    depends_on:
      - lms-mongo
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://lms-mongo:27017/lms
      - SECRET_KEY=my-secret-key
      - TOKEN_DURATION=1h

  lms-dev-server:
    container_name: lms-dev-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - lms-mongo
    ports:
      - 8000:5000
    restart: on-failure
    volumes:
      - ./server/src:/code/src
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://lms-mongo:27017/lms
      - SECRET_KEY=my-secret-key
      - TOKEN_DURATION=1h

  lms-mongo:
    image: mongo
    ports:
      - 27017:27017
